---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: "chef"
  product_version: "13.8.5"

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    driver:
      provision_command:
        - yum update -y
        - yum install -y wget
        - yum install -y firewalld
        - yum install -y lsof
    run_list:
      - recipe[mb_wapp_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
